management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
   name: server
  profiles:
    active: server1
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: false
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85